spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/p2p_financial

server:
  port: 2020
  max-http-header-size: 10000000
  
filepath:
  snapshotFileBasePath: D:\p2p_financial\data\app\p2p_financial\snapshot
  jFileBasePath: D:\p2p_financial\data\app\p2p_financial\journal